### ISSUE TITLE
Question about where the injection happens

### ISSUE THREAD

**Issue by eldamir** [eyaldror/di_container#6]
So from the description and example, I understand how we register implementations to type and names, etc. and I see how dependencies are declared in constructors in the example. All good... But where does the actual injection happen?

I'm strugging to find where the entry point to the function is..

There is a `main` function which is strapped into the container, but where does program execution start, and where does the container come into play?

When the container [resolves the name](https://github.com/eyaldror/di_container/blob/8782d802f3bf9cea5465ce77f04dcf967620b434/example/bootstrap.py#L48), is the function being called immediately after resolving?

**Comment by eyaldror** [comment]
Hi eldamir,

Resolving invokes what's being resolved (if there's no cached version, or the instantiation is MultiInstance).
If the callable is a type, as it usually is, it'll invoke the constructor/initializer and you'll get the new instance. If the callable is a function, it'll be invoked and return its return value. In this case, resolving `main_function` invokes the main function starts the whole program.
You don't have to use the container for invoking the main function, though. You can resolve its dependencies and call it manually.

I hope that answered your question 🙂

**Comment by eldamir** [comment]
Alright great, then it works as I would assume. it was simply hard to track that fact in the code here.

Thank you for making this! I think it could be very useful for decoupling stuff in a similar way to what statically typed languages are doing 😉

**Comment by eyaldror** [comment]
Thank you for commenting 😊 
If you end up using `di_container`, please, open issues with problems and suggestions that you find/think of.
